[tool.poetry]
name = "flask-valid"
version = "0.1.1"
description = "Flask validator use pydantic"
authors = ["chaojie <zhuzhezhe95@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "flask_valid"}]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^2.1.3"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
mkdocs = "1.2.4"
mkdocs-material = "8.0.0"
pytest = "^7.1.2"
flake8 = "^4.0.1"
black = "^22.6.0"
isort = "^5.10.1"
coverage = "^6.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"